function myplot(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-May-2018 19:52:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.772439024390244 0.815]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','theta');
set(plot1(2),'DisplayName','alpha');

% Create ylabel
ylabel('theta and alpha, ^o');

% Create xlabel
xlabel('time, ms');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 4000]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

